# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OwnRadio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OwnRadio

  target 'OwnRadioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OwnRadioUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'AppCenter'
